# Generated by Django 5.0.3 on 2024-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_link', models.URLField()),
                ('district', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('visited', models.BooleanField(default=False)),
                ('rate', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
